sudo: required
language: java

serivces:
  - docker

before_install:
 - docker build -t yasinb/libman-hex-app -f Dockerfile.dev .

script:
  - docker run yasinb/libman-hex-app
  - docker run yasinb/libman-hex-app mvn integration-test

after_success:
 - docker build -t yasinb/libman-hex-app .
 - docker build -t yasinb/libman-hex-proxy ./nginx
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
 - docker push yasinb/libman-hex-app
 - docker push yasinb/libman-hex-proxy

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'libman'
  env: 'Libman-env'
  bucket_name: 'elasticbeanstalk-us-east-2-948261954108'
  bucket_path: 'libman'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
