sudo: required
language: java

serivces:
  - docker

before_install:
 - docker build -t yasinb/libman-hex -f Dockerfile.dev .

script:
  - docker run yasinb/libman-hex
  - docker run yasinb/libman-hex mvn integration-test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'libman'
  env: 'Libman-env'
  bucket_name: 'elasticbeanstalk-us-east-2-948261954108'
  bucket_path: 'libman'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
