sudo: required
language: java

serivces:
  - docker

before_install:
 - docker build -t yasinb/libman-hex -f Dockerfile.dev .

script:
  - docker run yasinb/libman-hex
  - docker run yasinb/libman-hex mvn integration-test
