version: '3'

services:
  postgres:
    image: "postgres:9.6-alpine"
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=libmandb
      - POSTGRES_USER=libman-user
      - POSTGRES_PASSWORD=libman

  library:
    build: .
    container_name: library
    hostname: library
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=libmandb
      - POSTGRES_USER=libman-user
      - POSTGRES_PASSWORD=libman
    depends_on:
      - postgres

  proxy:
    restart: always
    container_name: proxy
    hostname: proxy
    build:
      context: ./nginx
    ports:
    - 80:80
    depends_on:
      - library

volumes:
  postgres-data:
